# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49276b438888a9b15f4c390f4019bbb248f8f5a5a9c12280e360fc6a668697542296af59e96d0ee66869a7ad544ccbf5c134605f360390b345bf24550f2b811c

test:
  secret_key_base: c034fe04aa4386a154ffea552386c33742c2d9797f5fa2699948e466d20e30fce7b05d773411b5d9181e86e64fc32bdfe44c594ffcab4e504cc1ff68f5066678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
